system:
  db_file: 1Panel.db
  base_dir: /opt
  mode: dev
  repo_url: https://resource.1panel.pro
  # app_repo: https://apps.1panel.pro
  # app_repo: http://127.0.0.1:8900
  app_repo: http://192.188.100.101:8888
  use_local_asserts: true
  local_asserts: /usr/local/deploy/magic-runner/asserts/cache/dev/1panel
  is_demo: false
  is_intl: true
  port: 9999
  username: admin
  password: admin123

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
