system:
  db_file: 1Panel.db
  base_dir: /opt
  mode: stable
  repo_url: https://resource.1panel.pro
  # app_repo: https://apps.1panel.pro
  # app_repo: http://127.0.0.1:8900
  app_repo: http://192.188.100.101:8888
  is_replace_download_url: true
  use_local_assets: true
  local_assets: /usr/local/deploy/1panel_assets/stable/1panel
  is_demo: false
  is_intl: true
  port: 9999
  username: admin
  password: admin123
  # Only support mysql or sqlite
  db_type: mysql
  dsn: root:123456@tcp(192.188.100.101:3336)/1panel?charset=utf8mb4&parseTime=True&loc=Local

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
